### ISSUE TITLE
Support Kotlin

### ISSUE THREAD

**Issue by BornForFever** [massivemadness/ModPE-IDE#4]
I'm a kotlin learner and is writing code on ModPE IDE. As you can see, however, the code isn't highlighted. I would be more than grateful if you can support Kotlin! 
![Screenshot_20200725_194000_com KillerBLS modpeide](https://user-images.githubusercontent.com/62426149/88456308-2b57e280-ceaf-11ea-860c-d44994dc53a0.jpg)

**Comment by massivemadness** [comment]
Hi, it's easy to integrate syntax highlighting for any language, because you just need to implement [Language](https://github.com/massivemadness/ModPE-IDE/blob/master/languages/language/src/main/kotlin/com/lightteam/language/language/Language.kt) interface and make some changes in [LanguageDelegate](https://github.com/massivemadness/ModPE-IDE/blob/master/data/src/main/kotlin/com/lightteam/modpeide/data/delegate/LanguageDelegate.kt)'s `provideLanguage` method.

But anyway, this editor was created **only for ModPE Script**, and I don't have any plans to add more languages, at least as long as I have some important tasks in [Roadmap](https://github.com/massivemadness/ModPE-IDE/projects/1).

**Comment by massivemadness** [comment]
https://github.com/massivemadness/Brackeys-IDE/commit/67c691b760ee3993677be64323301c8d318a4e96
